library(Seurat)
library(dplyr)
library(cowplot)
library(Biobase)
library(knitr)
library(reshape2)
library(ggplot2)
library(HSMMSingleCell)
library(monocle)
pbmc <-readRDS("seurat_analysis_less_dim20_res0.3_markers.rds")
data_expr <- as(as.matrix(pbmc@assays$RNA@counts), 'sparseMatrix')
data_pd <- read.table('phenoData.txt', header = T, row.names = 1)
pd <- new("AnnotatedDataFrame", data = data_pd)
data_fd <- read.table('featureData.txt', header = T, row.names = 1)
fd <- new("AnnotatedDataFrame", data = data_fd)
cds <- newCellDataSet(as.matrix(data_expr), phenoData = pd, featureData = fd)
cds <- estimateSizeFactors(cds)
cds <- estimateDispersions(cds)
diff_test_res <- differentialGeneTest(cds, fullModelFormulaStr = "~cluster")
ordering_genes <- row.names(subset(diff_test_res, qval < 0.01))
cds <- setOrderingFilter(cds, ordering_genes)
cds <- reduceDimension(cds, max_components = 2, method = 'DDRTree')
cds <- orderCells(cds)
pdf(file = "pseudotime_dGT_cell.pdf")
plot_cell_trajectory(cds, color_by = "cluster")
dev.off()
saveRDS(cds,file = "pseudotime_dGT_cell.rds")
write.table(pData(cds), file = 'pseudotime_pData_cell.txt', col.names = T, row.names = T)

