library(Seurat)
library(dplyr)
library(cowplot)
data <- read.table(file = "out_gene_exon_tagged_15000.dge.txt", header = T, row.names= 1)
pbmc <- CreateSeuratObject(counts = data, min.cells = 3, min.features  = 200, project = "cells", assay = "RNA")
mito.genes <- grep(pattern = "^MT-", x = rownames(pbmc@assays[["RNA"]]), value = TRUE)
percent.mito <- Matrix::colSums(pbmc@assays[["RNA"]][mito.genes, ])/Matrix::colSums(pbmc@assays[["RNA"]])
pbmc <- AddMetaData(object = pbmc, metadata = percent.mito, col.name = "percent.mito")
pbmc$percent.mito <- percent.mito
pdf(file = "VlnPlot_Feature_Count_percent.mito.pdf")
VlnPlot(object = pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mito"), ncol = 3)
dev.off()
pdf(file = "FeatureScatter_Count_percent.mito+Feature.pdf")
par(mfrow = c(1, 2))
FeatureScatter(object = pbmc, feature1 = "nCount_RNA", feature2 = "percent.mito")
FeatureScatter(object = pbmc, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
dev.off()
pbmc <- subset(x = pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mito >  -Inf & percent.mito < 0.2)
pbmc <- NormalizeData(object = pbmc, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc <- FindVariableFeatures(object = pbmc, mean.function = ExpMean, dispersion.function = LogVMR, x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.5, nfeatures = 2000)
pbmc <- ScaleData(object = pbmc, vars.to.regress = c("nCounts_RNA", "percent.mito"))
pbmc <- RunPCA(object = pbmc,  npcs = 30, verbose = FALSE)
pdf(file = "pca_ElbowPlot.pdf")
ElbowPlot(object = pbmc)
dev.off()
pbmc <- FindNeighbors(pbmc, reduction = "pca", dims = 1:10)
pbmc <- FindClusters(pbmc, resolution = 0.5, algorithm = 1)
pdf(file = "pca_res0.5_dim10.pdf")
DimPlot(object = pbmc, reduction = "pca")
dev.off()
pbmc <- RunTSNE(object = pbmc, dims.use = 1:10, do.fast = TRUE)
pdf(file = "tSNE_res0.5_dim10.pdf")
DimPlot(object = pbmc, reduction = "tsne")
dev.off()
pbmc <- RunUMAP(pbmc, reduction = "pca", dims = 1:10)
pdf(file = "UMAP_res0.5_dim10.pdf")
DimPlot(pbmc, reduction = "umap")
dev.off()
pbmc.markers <- FindAllMarkers(object = pbmc, only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25)
write.table(pbmc.markers,file="markers_res0.5_dim10.txt" , sep ="\t", row.names =TRUE, col.names =TRUE, quote =FALSE)
saveRDS(pbmc, file = "seurat_analysis_none_res0.5_dim10.rds")

pbmc <- FindNeighbors(pbmc, reduction = "pca", dims = 1:10)
pbmc <- FindClusters(pbmc, resolution = 0.8, algorithm = 1)
pdf(file = "pca_res0.8_dim10.pdf")
DimPlot(object = pbmc, reduction = "pca")
dev.off()
pbmc <- RunTSNE(object = pbmc, dims.use = 1:10, do.fast = TRUE)
pdf(file = "tSNE_res0.8_dim10.pdf")
DimPlot(object = pbmc, reduction = "tsne")
dev.off()
pbmc <- RunUMAP(pbmc, reduction = "pca", dims = 1:10)
pdf(file = "UMAP_res0.8_dim10.pdf")
DimPlot(pbmc, reduction = "umap")
dev.off()
pbmc.markers <- FindAllMarkers(object = pbmc, only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25)
write.table(pbmc.markers,file="markers_res0.8_dim10.txt" , sep ="\t", row.names =TRUE, col.names =TRUE, quote =FALSE)
saveRDS(pbmc, file = "seurat_analysis_none_res0.8_dim10.rds")

